apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  namespace: prod 
spec: 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: hazemhashem100/web:latest
        ports:
        - containerPort: 80
